name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: self-hosted  # EC2에서 실행

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew  # Ensure gradlew is executable

      - name: Gradle 빌드
        run: |
          ./gradlew bootJar --no-daemon --parallel --build-cache --configure-on-demand

      - name: Docker 이미지 빌드
        run: |
            # Docker 빌드 컨텍스트 확인
            echo "현재 경로: $(pwd)"
            docker build -t my-app .  # Dockerfile이 현재 디렉토리에 있어야 합니다.
      - name: Docker 컨테이너 실행
        run: |
          # 기존 컨테이너가 있을 경우 종료하고 삭제
          docker ps -q --filter "name=my-app-container" | xargs -r docker stop | xargs -r docker rm
          
          # 새로운 컨테이너 실행
          docker run -d -p 8080:8080 --name my-app-container my-app

      - name: Clean up
        run: docker system prune -f  # 불필요한 Docker 이미지와 컨테이너를 정리합니다.
